import './(pages)/_globals/globals.scss';
import Header from './(pages)/_components/Header/Header';
import Footer from './(pages)/_components/Footer/Footer';
import { ThemeProvider } from './_context/ThemeContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       
        <Header />
        <ThemeProvider>{children}</ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}