import './(pages)/_globals/globals.scss';
import Header from './(pages)/_components/Header/Header';
import Footer from './(pages)/_components/Footer/Footer';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}